# Generated by Django 4.1.4 on 2022-12-08 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_remove_category_subcategories'),
        ('subcategories', '0002_remove_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category'),
            preserve_default=False,
        ),
    ]
