# Generated by Django 4.1.4 on 2022-12-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.FloatField(default=5000),
        ),
    ]
