# Generated by Django 4.1.4 on 2022-12-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_alter_user_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet',
        ),
    ]
