# Generated by Django 4.1.4 on 2022-12-07 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.FloatField(default=False, max_length=100),
        ),
    ]
