# Generated by Django 4.1.4 on 2022-12-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('duration', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('item_image', models.URLField(blank=True, default=None, max_length=300, null=True)),
                ('categories', models.ManyToManyField(related_name='items', to='categories.category')),
            ],
        ),
    ]
