# Generated by Django 4.1.4 on 2022-12-14 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0003_listings_buyer_alter_listings_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='buyer',
            field=models.ForeignKey(default='Jeff', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Purchases',
        ),
    ]
