# Generated by Django 4.1.4 on 2022-12-08 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='subcategories',
        ),
    ]
