# Generated by Django 4.1.4 on 2022-12-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='profile_image',
            field=models.URLField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
