# Generated by Django 4.1.4 on 2022-12-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_item_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='profile_image',
            new_name='item_image',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
