# Generated by Django 4.1.4 on 2022-12-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_rename_profile_image_item_item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
