# Generated by Django 4.1.4 on 2022-12-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_item_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='duration',
            field=models.FloatField(),
        ),
    ]
