# Generated by Django 4.1.4 on 2022-12-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0002_remove_subcategory_category'),
        ('categories', '0002_category_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ManyToManyField(related_name='items', to='subcategories.subcategory'),
        ),
    ]
