# Generated by Django 4.1.4 on 2022-12-08 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subcategories', '0002_remove_subcategory_category'),
        ('categories', '0003_remove_category_subcategories_category_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='category',
            name='subcategories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='subcategories.subcategory'),
            preserve_default=False,
        ),
    ]
